#!/bin/bash

## Exit immediately on error.
set -e

# Echo to console.
set -x

for DIR in ./ ./dev
do
  pushd $DIR
  docker build \
    --tag siaprime-image \
    .

  export DUMMY_DATA_DIR=$(mktemp -d)

  # Run container in detached state
  docker run \
    --detach \
    --publish 127.0.0.1:4280:4280 \
    --volume "${DUMMY_DATA_DIR}:/siaprime-data" \
    --env SIAPRIME_MODULES=cg \
    --name siaprime-container \
    siaprime-image

  sleep 5s

  if [ -e "${DUMMY_DATA_DIR}/consensus" ]; then
    (echo "Created consensus folder successfully" && exit 0)
  else
    (echo "Couldn't find consensus folder" && \
      docker logs siaprime-container && \
      exit 1)
  fi

  curl -A "SiaPrime-Agent" "http://localhost:4280/consensus"

  docker rm -f siaprime-container
  popd
done
